---
- name: Editing /grub/conf
  hosts: all

  tasks:
  - name: adding parameter net.ifnames=0 in /etc/default/grub
    lineinfile:
      state: present
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* net.ifnames)\"[^\"]+)(\".*)'
      line: '\1 net.ifnames=0\2'
      backrefs: yes
    notify:
    - Update Grub2 config file

  - name: Check if parameter net.ifnames has "0" value
    replace:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
      replace: '\1 {{ option }}={{ value }}\2'
    vars:
      option: net.ifnames
      value: 0
    notify:
    - Update Grub2 config file

  - name: adding parameters biosdevname=0 in /etc/default/grub
    lineinfile:
      state: present
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.* biosdevname)\"[^\"]+)(\".*)'
      line: '\1 biosdevname=0\2'
      backrefs: yes
    notify:
    - Update Grub2 config file

  - name: Check if parameter biosdevname has "0" value
    replace:
      path: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?:(?![" ]{{ option | regex_escape }}=).)*)(?:[" ]{{ option | regex_escape }}=\S+)?(.*")$'
      replace: '\1 {{ option }}={{ value }}\2'
    vars:
      option: biosdevname
      value: 0
    notify:
    - Update Grub2 config file

  handlers:
    - name: Update Grub2 config file
      shell: grub2-mkconfig -o /etc/default/grub
...
