---
- name: creating users
  hosts: node1.example.com
  gather_facts: false
  vars_files:
    - users.yml

  tasks:
    - name: create users
      ansible.builtin.user:
        name: "{{ item.key }}"
        state: present
        update_password: on_create
        home: "/home/{{ item.key }}" 
        comment: "{{ item.key }}@exaple.com"
        password: "{{ item.value.pass | password_hash('sha512') }}"
      with_dict: "{{ users_with_dict }}"
...
